export const quizData = [
  {
    id: 1,
    question: "Qui sont M. Dupont et Mlle Sicart ?",
    image: "/images/courses/breaklunch.png",
    correctAudio: "/audios/correct.mp3",
    wrongAudio: "/audios/wrong.mp3",
    choices: [
      {
        id: "A",
        label: "Des amis",
        isCorrect: false,
        explanationCorrect: "",
        explanationWrong: "Non, ils ne sont pas amis.",
      },
      {
        id: "B",
        label: "Des frères et sœur",
        isCorrect: false,
        explanationCorrect: "",
        explanationWrong: "Non, ils ne sont pas de la même famille.",
      },
      {
        id: "C",
        label: "Des collègues de travail",
        isCorrect: true,
        explanationCorrect: "Exact, ils travaillent ensemble.",
        explanationWrong: "",
      },
    ],
  },
  {
    id: 2,
    question: "M. Dupont est marié, divorcé ou célibataire ?",
    image: "/images/courses/breaklunch.png",
    correctAudio: "/audios/correct.mp3",
    wrongAudio: "/audios/wrong.mp3",
    choices: [
      {
        id: "A",
        label: "Marié",
        isCorrect: true,
        explanationCorrect: "Oui, il est marié.",
        explanationWrong: "",
      },
      {
        id: "B",
        label: "Divorcé",
        isCorrect: false,
        explanationCorrect: "",
        explanationWrong: "Non, il n'est pas divorcé.",
      },
      {
        id: "C",
        label: "Célibataire",
        isCorrect: false,
        explanationCorrect: "",
        explanationWrong: "Non, il n'est pas célibataire.",
      },
    ],
  },
  {
    id: 3,
    question:
      "Le samedi, M. Dupont fait le ménage et la cuisine, les courses et la cuisine ou la vaisselle et la cuisine ?",
    image: "/images/courses/breaklunch.png",
    correctAudio: "/audios/correct.mp3",
    wrongAudio: "/audios/wrong.mp3",
    choices: [
      {
        id: "A",
        label: "Le ménage et la cuisine",
        isCorrect: false,
        explanationCorrect: "",
        explanationWrong: "Non, ce n’est pas cela.",
      },
      {
        id: "B",
        label: "Les courses et la cuisine",
        isCorrect: true,
        explanationCorrect: "Exact, il fait les courses et la cuisine.",
        explanationWrong: "",
      },
      {
        id: "C",
        label: "La vaisselle et la cuisine",
        isCorrect: false,
        explanationCorrect: "",
        explanationWrong: "Non, ce n’est pas la bonne réponse.",
      },
    ],
  },
  {
    id: 4,
    question: "Qui fait le ménage chez M. Dupont ?",
    image: "/images/courses/breaklunch.png",
    correctAudio: "/audios/correct.mp3",
    wrongAudio: "/audios/wrong.mp3",
    choices: [
      {
        id: "A",
        label: "Sa mère",
        isCorrect: false,
        explanationCorrect: "",
        explanationWrong: "Non, ce n’est pas sa mère.",
      },
      {
        id: "B",
        label: "Sa fille",
        isCorrect: false,
        explanationCorrect: "",
        explanationWrong: "Non, ce n’est pas sa fille.",
      },
      {
        id: "C",
        label: "Sa femme",
        isCorrect: true,
        explanationCorrect: "Oui, c’est sa femme.",
        explanationWrong: "",
      },
    ],
  },
  {
    id: 5,
    question: "M. Dupont mange au bar ou au restaurant ?",
    image: "/images/courses/breaklunch.png",
    correctAudio: "/audios/correct.mp3",
    wrongAudio: "/audios/wrong.mp3",
    choices: [
      {
        id: "A",
        label: "Au bar",
        isCorrect: false,
        explanationCorrect: "",
        explanationWrong: "Non, il ne mange pas au bar.",
      },
      {
        id: "B",
        label: "Au restaurant",
        isCorrect: true,
        explanationCorrect: "Exact, il mange au restaurant.",
        explanationWrong: "",
      },
    ],
  },
  {
    id: 6,
    question: "À midi, Mlle Sicart va au centre commercial ou à la piscine ?",
    image: "/images/courses/breaklunch.png",
    correctAudio: "/audios/correct.mp3",
    wrongAudio: "/audios/wrong.mp3",
    choices: [
      {
        id: "A",
        label: "Au centre commercial",
        isCorrect: false,
        explanationCorrect: "",
        explanationWrong: "Non, ce n’est pas la bonne réponse.",
      },
      {
        id: "B",
        label: "À la piscine",
        isCorrect: true,
        explanationCorrect: "Oui, elle va à la piscine.",
        explanationWrong: "",
      },
    ],
  },
  {
    id: 7,
    question:
      "Le dimanche, M. Dupont fait du sport avec un ami ou avec sa femme ?",
    image: "/images/courses/breaklunch.png",
    correctAudio: "/audios/correct.mp3",
    wrongAudio: "/audios/wrong.mp3",
    choices: [
      {
        id: "A",
        label: "Avec un ami",
        isCorrect: false,
        explanationCorrect: "",
        explanationWrong: "Non, ce n’est pas avec un ami.",
      },
      {
        id: "B",
        label: "Avec sa femme",
        isCorrect: true,
        explanationCorrect: "Exact, il fait du sport avec sa femme.",
        explanationWrong: "",
      },
    ],
  },
  {
    id: 8,
    question: "Qu’est-ce qu’ils font ?",
    image: "/images/courses/breaklunch.png",
    correctAudio: "/audios/correct.mp3",
    wrongAudio: "/audios/wrong.mp3",
    choices: [
      {
        id: "A",
        label: "Du yoga",
        isCorrect: false,
        explanationCorrect: "",
        explanationWrong: "Non, ce n’est pas du yoga.",
      },
      {
        id: "B",
        label: "De la randonnée",
        isCorrect: true,
        explanationCorrect: "Oui, ils font de la randonnée.",
        explanationWrong: "",
      },
      {
        id: "C",
        label: "De l’escalade",
        isCorrect: false,
        explanationCorrect: "",
        explanationWrong: "Non, ce n’est pas cela.",
      },
    ],
  },
  {
    id: 9,
    question: "Où est-ce qu’ils vont pour faire cette activité ?",
    image: "/images/courses/breaklunch.png",
    correctAudio: "/audios/correct.mp3",
    wrongAudio: "/audios/wrong.mp3",
    choices: [
      {
        id: "A",
        label: "À la montagne",
        isCorrect: true,
        explanationCorrect: "Exact, ils vont à la montagne.",
        explanationWrong: "",
      },
      {
        id: "B",
        label: "À la campagne",
        isCorrect: false,
        explanationCorrect: "",
        explanationWrong: "Non, ce n’est pas la campagne.",
      },
      {
        id: "C",
        label: "À la salle de sport",
        isCorrect: false,
        explanationCorrect: "",
        explanationWrong: "Non, ce n’est pas la salle de sport.",
      },
    ],
  },
  {
    id: 10,
    question: "Où va Mlle Sicart le samedi soir ?",
    image: "/images/courses/breaklunch.png",
    correctAudio: "/audios/correct.mp3",
    wrongAudio: "/audios/wrong.mp3",
    choices: [
      {
        id: "A",
        label: "Au cinéma",
        isCorrect: false,
        explanationCorrect: "",
        explanationWrong: "Non, elle ne va pas au cinéma.",
      },
      {
        id: "B",
        label: "En boîte",
        isCorrect: true,
        explanationCorrect: "Oui, elle va en boîte.",
        explanationWrong: "",
      },
    ],
  },
  {
    id: 11,
    question: "Pourquoi M. Dupont va au restaurant ?",
    image: "/images/courses/breaklunch.png",
    correctAudio: "/audios/correct.mp3",
    wrongAudio: "/audios/wrong.mp3",
    choices: [
      {
        id: "A",
        label: "Pour dormir",
        isCorrect: false,
        explanationCorrect: "",
        explanationWrong: "Non, il ne va pas dormir.",
      },
      {
        id: "B",
        label: "Pour déjeuner",
        isCorrect: true,
        explanationCorrect: "Exact, il va au restaurant pour déjeuner.",
        explanationWrong: "",
      },
    ],
  },
  {
    id: 12,
    question: "Pourquoi Mlle Sicart va à la piscine ?",
    image: "/images/courses/breaklunch.png",
    correctAudio: "/audios/correct.mp3",
    wrongAudio: "/audios/wrong.mp3",
    choices: [
      {
        id: "A",
        label: "Pour nager",
        isCorrect: false,
        explanationCorrect: "",
        explanationWrong: "Non, ce n’est pas la raison principale.",
      },
      {
        id: "B",
        label: "Pour faire de la gymnastique dans l’eau",
        isCorrect: true,
        explanationCorrect: "Exact, elle fait de la gymnastique dans l’eau.",
        explanationWrong: "",
      },
    ],
  },
];
